GET http://localhost:3000/inventory-query/products

###
GET http://localhost:3000/inventory-query/products/SKU-001-TLB


###
POST http://localhost:3000/inventory-command/order/
Content-Type: application/json
{
    "sku": "SKU-001-TLB",
    "version": 3,
    "wantedQuantity": 5
}
